#!/usr/bin/env bash

digger () {
    RTYPE=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $4}')
    DESTI=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $5}')
    echo The subdomain "$2" is a "$RTYPE" record and points to "$DESTI"
}
if [ "$2" ];
    then
	digger "$2.$1" "$2"
else
	digger "www.$1" www
	digger "lb-01.$1" lb-01
	digger "web-01.$1" web-01
	digger "web-02.$1" web-02
fi
exit 0
