#!/usr/bin/env bash
#This scripts configures a redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee '/var/www/html/index.nginx-debian.html'
cat > '/etc/nginx/sites-available/default' <<EOF
server {

       server_name .tyedge.tech;

       listen 80;
       listen [::]:80;

       root /var/www/html;
       index index.nginx-debian.html;

       location /redirect_me {
              rewrite ^/redirect_me$ https://example.com permanent;
       }
}
EOF
service nginx reload
service nginx restart
