#!/usr/bin/env bash
#This scripts configures an nginx web server on a remote server
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee '/var/www/html/index.nginx-debian.html'
cat > '/etc/nginx/sites-enabled/default' <<EOF
server {
       listen 80;
       listen [::]:80;

       root /var/www/html;
       index index.html;

       location /redirect_me {
              return 301 https://example.com;
       }
}
EOF
service nginx reload
service nginx restart
