#!/usr/bin/env bash
#This scripts configures a new server with a custom HTTP response header
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee '/var/www/html/index.nginx-debian.html'
sudo echo 'Ceci n'\''est pas une page' | sudo tee '/var/www/html/404.html'
cat > '/etc/nginx/sites-available/default' <<EOF
server {
       server_name .tyedge.tech;
       listen 80;
       listen [::]:80;
       add_header X-Served-By $(hostname);
       root /var/www/html;
       index index.nginx-debian.html;
       error_page 404 /404.html;
       location /404.html {
                internal;
       }
       location /redirect_me {
              rewrite ^/redirect_me$ https://example.com permanent;
       }
}
EOF
service nginx reload
service nginx start
