#!/usr/bin/env bash
# This script adds the correct server and port info to sites enabled and
#+ restart nginxs
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -t && sudo service nginx restart
