#!/usr/bin/env bash
#This script displays numbers from 1 to 100
num=0
while [ $num -lt 100 ]
do
    (( num=num + 1 ))
    if ((num % 3 == 0)) && ((num % 5 == 0))
    then
	echo "FizzBuzz"
    elif ((num % 3 == 0))
    then
	echo "Fizz"
    elif ((num % 5 == 0))
    then
	echo "Buzz"
    else
	echo $num
fi
done
