#!/usr/bin/env bash
#This script loops from 1 to 10 and displays bad luck for the 4th loop
#+ iteration, displays good luck for the 8th loop iteration, and diplays
#+ displays Holberton School for the other iterations
i=1

while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
	(( i++ ))
    elif [ $i -eq 8 ]
    then
	echo "good luck"
	(( i++ ))
    else
	echo "Holberton School"
	(( i++ ))
    fi
done
