#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes
hour=0
minute=1

while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    while [ $hour -lt 13 ] && [ $minute -lt 60 ]
    do
	echo -n "$minute" $'\n'
	: $(( minute++ ))
    done
    minute=1
    : $(( hour++ ))
done
