#!/usr/bin/env bash
# This script configures edits the etc/hosts file to change the IP addresses of
#+ localhost and facebook.com

cp /etc/hosts /tmp/new_hosts | grep -vx '127.*localhost' /etc/hosts > /tmp/thosts
echo '127.0.0.2 localhost' > /tmp/new_hosts
echo '8.8.8.8 facebook.com' >> /tmp/new_hosts
cat /tmp/thosts >> /tmp/new_hosts
cp /tmp/new_hosts /etc/hosts
rm /tmp/new_hosts
rm /tmp/thosts
