#!/usr/bin/env bash
# This script configures edits the etc/hosts file to change the IP addresses of
#+ localhost and facebook.com
cp /etc/hosts ~/hosts.new
sed -i s/^172..*$// ~/hosts.new
sed -i s/^852.*$// ~/hosts.new
cp -f ~/hosts.new /etc/hosts
