#!/usr/bin/env bash
#This script resolves the issue: "AH00558: apache2: Could not reliably
#determine the server's fully qualified domain name, using 172.17.0.2. Set the\
#'ServerName' directive globally to suppress this message"
echo 'ServerName localhost' >> /etc/apache2/apache2.conf
service apache2 restart
